# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Setup environment
      run: docker-compose up -d db

    - name: Setup golang-migrate
      run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@$TAG

    - name: Run migrations
      run: migrate -database "postgres://root:somepassword@localhost:5432/statsdb?sslmode=disable" -path pkg/database/migrations up

    - name: Test
      run: go test -v ./...
      env:
        DATABASE_HOSTNAME: localhost
        DATABASE_USER: root
        DATABASE_PASSWORD: somepassword
        DATABASE_PORT: 5432
        DATABASE_NAME: statsdb
